#!/usr/bin/bash


export VERSION=1.19.5 OS=linux ARCH=amd64 &&     wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz &&     sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz &&     rm go$VERSION.$OS-$ARCH.tar.gz
echo "export PATH=/usr/local/go/bin/:$PATH" > alldone.sh
echo "export LD_LIBRARY_PATH=/usr/local/go/lib/:$LD_LIBRARY_PATH" >> alldone.sh
chmod +x alldone.sh
./alldone.sh



VERSION=3.10.5 
GOPATH=/usr/local/singularityi1/
mkdir -p $GOPATH/src/github.com/sylabs
cd $GOPATH/src/github.com/sylabs
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz
tar -xzf singularity-ce-${VERSION}.tar.gz
cd ./singularity-ce-${VERSION}
sudo ./mconfig
